replicaCount: 3

service:
  type: LoadBalancer
  port: 80

image:
  repository: <NODE_SERVICE_REPO>
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  #   tag: ${BUILDRUN_HASH}
  #
